//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSAuthentication.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        public Accounts()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int AccountID { get; set; }
        public string AccountName { get; set; }
        public byte[] OwnerEmail { get; set; }
        public string OwnerPhone { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string AccountContact { get; set; }
    
        public virtual ICollection<Products> Products { get; set; }
    }
}
