//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSAuthentication.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSubcategory
    {
        public int ProductID { get; set; }
        public int SubcategoryID { get; set; }
        public int ID { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Subcategories Subcategories { get; set; }
    }
}
