//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSAuthentication.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.ProductSubcategory = new HashSet<ProductSubcategory>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public bool OnSale { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int AccountID { get; set; }
        public int CategoryID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public string Description { get; set; }
        public Nullable<int> Units { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual ICollection<ProductSubcategory> ProductSubcategory { get; set; }
    }
}
