//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSAuthentication.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subcategories
    {
        public Subcategories()
        {
            this.ProductSubcategory = new HashSet<ProductSubcategory>();
        }
    
        public int SubcategoryID { get; set; }
        public int CategoryID { get; set; }
        public string SubcategoryName { get; set; }
        public bool IsActive { get; set; }
        public string Description { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual ICollection<ProductSubcategory> ProductSubcategory { get; set; }
    }
}
